repos:
-
  repo: local
  hooks:
    -
      id: flutter-format
      name: Flutter Format
      entry: fvm flutter format --dry-run --set-exit-if-changed
      language: system
      files: \.dart$
-
  repo: local
  hooks:
    -
      id: flutter-analyze
      name: Flutter Analyze
      entry: fvm flutter analyze
      language: system
      files: \.dart$
      pass_filenames: false
-
  repo: local
  hooks:
    -
      id: flutter-import-sorter
      name: Flutter Import Sorter
      entry: fvm flutter pub run import_sorter:main --exit-if-changed
      language: system
      files: \.dart$
      require_serial: true
